# Workflow to publish the documentation website on github pages for tagged releases

name: Documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install package and documentation dependencies
        run: python -m pip install . sphinx

      - name: Build docs
        run: |
          sphinx-build -W --keep-going doc "${{ runner.temp }}/hallmark-docs"

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v4
        with:
          path: "${{ runner.temp }}/hallmark-docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4




